CREATE TABLE customersites(
	cocode char(1) NOT NULL,
	custmast char(10) NOT NULL,
	custnum numeric(9, 0) NOT NULL,
	startdate datetime NOT NULL,
	taxpcnt numeric(9, 3) NOT NULL,
	taxpcnt2 numeric(9, 3) NOT NULL,
	taxexempt char(20) NOT NULL,
	penalty numeric(8, 2) NOT NULL,
	po_num char(20) NOT NULL,
	d_waiver char(1) NOT NULL,
	sitename char(35) NOT NULL,
	siteaddr char(35) NOT NULL,
	siteaddr2 char(35) NOT NULL,
	sitecity char(25) NOT NULL,
	sitestate char(2) NOT NULL,
	sitezip char(10) NOT NULL,
	sitephone char(20) NOT NULL,
	sitefax char(20) NOT NULL,
	sitezip4 char(10) NOT NULL,
	sitecntry char(10) NOT NULL,
	super char(20) NOT NULL,
	bllmast char(10) NOT NULL,
	blladdr char(40) NOT NULL,
	blladdr2 char(40) NOT NULL,
	bllcity char(40) NOT NULL,
	bllemail1 char(124) NULL,
	bllemail2 char(124) NULL,
	bllfax char(20) NOT NULL,
	bllname char(40) NOT NULL,
	bllphone char(20) NOT NULL,
	bllstate char(2) NOT NULL,
	bllzip char(20) NOT NULL,
	bllcocode char(1) NOT NULL,
	bllcontact char(40) NOT NULL,
	bllcountry char(10) NOT NULL,
	acctstatus char(10) NOT NULL,
	accttype char(10) NOT NULL,
	county char(10) NOT NULL,
	custcode1 char(10) NOT NULL,
	terms char(10) NOT NULL,
	email char(124) NULL,
	email2 char(124) NULL,
	emaillst bit NOT NULL,
	nomail bit NOT NULL,
	nomailing numeric(10, 0) NOT NULL,
	FKjcustmast int NULL
)